// mocks generated by me
// in fluttour/test/domain/usecase/dummy_usecase_test.dart.
// do not run this file.

import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

void main() {
  group('describes what component you are testing', () {
    test('describes the purpose of the test or the current state of an object', () {
      // stub a mock method before interacting
      when('mock.doMock()').thenAnswer((_) => 'stub');
      // the expected result of the test
      expect('actual', 'matcher');
    });
  });
}